package ec.com.app.bundle.backend;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

//import org.springframework.cloud.client.loadbalancer.LoadBalanced;
import ec.com.app.bundle.backend.model.ContactSendMail;
import ec.com.app.bundle.backend.model.User;
import ec.com.app.bundle.backend.repository.UserRepository;
import ec.com.app.bundle.backend.service.ContactSendMailService;

@RestController    // This means that this class is a Controller
@RequestMapping(path="/") // This means URL's start with /demo (after Application path)
public class MainController {
	//	@LoadBalanced
	@Autowired // This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private UserRepository userRepository;
	@Autowired
	private ContactSendMailService contactSendMailService;

	//private final static String ERROR_PATH = "/error";



	@GetMapping(path="/add") // Map ONLY GET Requests
	public @ResponseBody String addNewUser (@RequestParam String name
			, @RequestParam String email) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request

		User n = new User();
		n.setName(name);
		n.setEmail(email);
		userRepository.save(n);
		return "Saved";
	}

	@GetMapping(path="/all")
	public @ResponseBody Iterable<User> getAllUsers() {
		// This returns a JSON or XML with the users
		return userRepository.findAll();
	}

	@GetMapping(path="/allContacts")
	public @ResponseBody Iterable<ContactSendMail> getContacts() {
		// This returns a JSON or XML with the users
		return contactSendMailService.findAll();
	}

	@RequestMapping(value="/allGetContacts", method = RequestMethod.GET,produces = MediaType.APPLICATION_JSON_VALUE)
	public ResponseEntity<List<ContactSendMail>> getAllContacts() {
		// This returns a JSON or XML with the users
		List<ContactSendMail> contacts = contactSendMailService.findAll();
		if(contacts.isEmpty()){
			return new ResponseEntity<List<ContactSendMail>>(HttpStatus.NO_CONTENT);
		}
		return new ResponseEntity<List<ContactSendMail>>(contacts, HttpStatus.OK);

	}

	@RequestMapping(value="/getContactById", method = RequestMethod.GET,produces = MediaType.APPLICATION_JSON_VALUE)
	public ResponseEntity<ContactSendMail> getContactById(@RequestParam String names) {
		// This returns a JSON or XML with the users
		ContactSendMail contacts = contactSendMailService.findByNames(names);
		if(contacts.equals(null)){
			return new ResponseEntity<ContactSendMail>(HttpStatus.NO_CONTENT);
		}
		return new ResponseEntity<ContactSendMail>(contacts, HttpStatus.OK);

	}

}
